# Create a suitable environment:
# mamba env create -f environment.yml 
# or 
# conda env create -f environment.yml

name : smmregrid
channels:
  - conda-forge
dependencies:
  - python>=3.8,<=3.14
  - ecCodes
  - numba
  - cdo>=2.5.0
  - pip
  - pip:
    - -e .[all]
